# Generated by Django 4.2 on 2023-04-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('M', 'Manager')], max_length=10)),
            ],
        ),
    ]
