# Generated by Django 4.2 on 2023-05-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
