# Generated by Django 4.2 on 2023-05-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_remove_user_lastname_remove_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
