# Generated by Django 4.2 on 2023-04-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('commentaire', models.TextField(null=True)),
                ('sponsor', models.CharField(max_length=50, null=True)),
                ('chargefte', models.FloatField()),
                ('deleted', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('I', 'In progress'), ('P', 'Planned'), ('C', 'Closed'), ('A', 'Audit')], default='In progress')),
                ('type', models.CharField(choices=[('P', 'Prod'), ('E', 'Enhacement'), ('Pr', 'Project'), ('S', 'Support')], default='Prod')),
                ('niveau', models.CharField(null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks')),
            ],
        ),
    ]
